import { promises as fs } from "fs";
import os from "os";
import path from "path";

/**
 * All recordings, transcripts and notes live in one folder on this computer.
 * Override with LECTURE_DATA_DIR in .env.local.
 * Default on Windows: C:\Users\<you>\LectureRecorder
 */
export function dataDir(): string {
  const configured = process.env.LECTURE_DATA_DIR?.trim();
  if (configured) return path.resolve(configured);
  return path.join(os.homedir(), "LectureRecorder");
}

export function coursesFile(): string {
  return path.join(dataDir(), "courses.json");
}

export function lecturesDir(): string {
  return path.join(dataDir(), "lectures");
}

export function lectureDir(id: string): string {
  return path.join(lecturesDir(), safeId(id));
}

export const lecturePaths = (id: string) => {
  const base = lectureDir(id);
  return {
    base,
    meta: path.join(base, "lecture.json"),
    /** Append-only live captions (one JSON object per line). */
    live: path.join(base, "live.jsonl"),
    /** Final, high-accuracy transcript. */
    transcript: path.join(base, "transcript.json"),
    notes: path.join(base, "notes.json"),
    flashcards: path.join(base, "flashcards.json"),
    chat: path.join(base, "chat.jsonl"),
    materials: path.join(base, "materials"),
    materialsIndex: path.join(base, "materials", "index.json"),
    audio: path.join(base, "audio"),
    /** Continuous master recording, appended while recording. Kept permanently. */
    master: path.join(base, "audio", "master.webm"),
    /** Short self-contained chunks used for live captions. Deleted after finalize. */
    liveChunks: path.join(base, "audio", "live"),
    /** ~10 minute self-contained chunks used for the accurate pass. Deleted after finalize. */
    passChunks: path.join(base, "audio", "pass"),
    exportDir: path.join(base, "export"),
  };
};

/** Ids are generated by this app, but never trust one that arrived over HTTP. */
export function safeId(id: string): string {
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) {
    throw new Error("Invalid id");
  }
  return id;
}

export async function ensureLectureDirs(id: string): Promise<void> {
  const p = lecturePaths(id);
  await fs.mkdir(p.liveChunks, { recursive: true });
  await fs.mkdir(p.passChunks, { recursive: true });
  await fs.mkdir(p.materials, { recursive: true });
}

export async function ensureDataDir(): Promise<void> {
  await fs.mkdir(lecturesDir(), { recursive: true });
}
